
from distutils.log import debug
from bandeiras import Estado
from pagina import Pagina
from noticia import Noticia
from flask import Flask, render_template, redirect

app = Flask(__name__)

listas_de_paginas_principais = [
    Pagina(0,'Covid-19: Brasil tem a maior média móvel de mortes em seis meses','/static/img/covid-news-1.jpg','O Brasil registrou 892 mortes por covid-19 nas últimas 24 horas, segundo o levantamento do consórcio de veículos de imprensa feito junto às secretarias estaduais de Saúde do país, neste sábado (12). Com isso, o total de óbitos pelo novo coronavírus subiu para 638.124.A média móvel de mortes nos últimos sete dias é de 894 por dia – a maior registrada até hoje. De acordo com o balanço deste sábado, o número de novos casos conhecidos de covid-19 de ontem pra hoje foi de 132.935, elevando o total de infectados para 27.424.975. A média móvel de casos do novo coronavírus nos últimos sete dias foi de 136.138 por dia, um recuo de 27% em relação aos casos registrados em 14 dias, apontando tendência de queda nos diagnósticos da doença. Os dados divulgados pelo consórcio de imprensa foram obtidos após uma parceria inédita entre “g1”, “O Globo”, “Extra”, “O Estado de S.Paulo”, “Folha de S.Paulo” e “UOL”, que passaram a trabalhar de forma colaborativa desde o dia 8 de junho de 2020 para reunir as informações necessárias nos 26 Estados e no Distrito Federal.'),
    Pagina(1,'Como estão as vacinas da Covid-19 específicas para a variante Ômicron','/static/img/covid-news-2jpg.jpg','Os vírus são microrganismos com estruturas relativamente simples, compostos basicamente de proteínas e de informações genéticas. Essa característica faz com que eles tenham uma alta capacidade de mutação. É o que acontece com o SARS-CoV-2, que já se desdobrou em centenas de linhagens diferentes. Uma delas é a variante Ômicron, identificada em novembro de 2021, e que se espalhou rapidamente pelo mundo. Desde então, laboratórios e farmacêuticas se mobilizaram para avaliar como desenvolver vacinas capazes de reduzir o alto contágio da variante. Nenhuma das atualizações dos imunizantes ainda está pronta, mas a cada dia parecemos estar mais pertos delas. A média móvel de casos do novo coronavírus nos últimos sete dias foi de 136.138 por dia, um recuo de 27% em relação aos casos registrados em 14 dias, apontando tendência de queda nos diagnósticos da doença.'), 
    Pagina(2,'Araraquara tem 2 mortes por Covid-19 e soma 655 óbitos; mais 365 casos são registrados','/static/img/covid-news-3.jpg','Araraquara (SP) registrou, neste domingo (13), mais duas mortes por Covid-19 e chega aos 655 óbitos em decorrência da doença desde o início da pandemia. As vítimas mais recentes são:idoso de 91 anos, com comorbidades, internado em hospital da rede particular desde o dia 4 de fevereiro.idoso de 69 anos, com comorbidades, internado em hospital da rede pública desde o dia 30 de janeiro. A cidade também registrou 365 novos casos da doença e soma 59.130 infectados desde o início da pandemia. Segundo o boletim do Comitê de Contingência do Coronavírus, o município tem taxa de ocupação de 56% de leitos de enfermaria e 69% de UTI.'),  
]

listas_de_paginas_recentes = [
    Pagina(3,'Covid-19: A maioria dos estados não apresentam média de crescimento na média de casos','/static/img/covid-news-4.jpg','Dados divulgados pelo Ministério da Saúde neste sábado (12) apontaram que o número de novos casos voltou a diminuir na maioria dos estados do país. Dentre os 26 estados mais o Distrito Federal, 14 apresentaram queda nas suas médias móveis de infecções e oito se mantiveram estáveis. Rio de Janeiro, Minas Gerais, Espírito Santo, Mato Grosso, Rio Grande do Sul, Santa Catarina, Paraná, Amapá, Roraima, Tocantins, Amazonas, Ceará, Rio Grande do Norte e o Distrito Federal registraram índices pelo menos 15% menores em relação há duas semanas. Ao mesmo tempo, o número médio de infecções em São Paulo, Goiás, Mato Grosso do Sul, Rondônia, Acre, Bahia, Maranhão e Pernambuco permaneceram estáveis em relação ao mesmo período. Desse modo, o panorama do Brasil se mantém em queda pelo segundo dia consecutivo após 44 dias com recordes de infecções. Com 140.234 novos casos, o número médio de brasileiros infectados chegou a 136.067, uma diminuição de 27% em relação há 14 dias. A análise da situação pandêmica é feita a partir da variação de 15% fixada por infectologistas como ponto de inflexão. Dessa maneira, se um índice registrar um aumento superior a 15% em relação há duas semanas, ele está em alta; se o índice cair mais de 15% em relação ao mesmo período, ele está em queda. Médias que permanecem entre -15% e 15% são definidas como estáveis.'),
    Pagina(4,'Covid-19: De onde poderá vir a próxima variante? Estudo aponta países prováveis','/static/img/covid-news-5.jpg','O vírus que causa a Covid-19 foi sequenciado pela primeira vez no início de 2020 e desde então já foram identificadas pela Organização Mundial de Saúde cinco "variantes preocupantes". A mais recente, a Ômicron, foi descoberta em novembro e é agora dominante em quase todos os países do mundo – a nova variante pode evitar a imunidade induzida pela vacina e se espalha mais rapidamente do que a Delta. No entanto, uma subvariante, a BA.2, parece ser ainda mais transmissível. Esta é a história que já vivemos, agora vamos à história que nos reserva – é improvável que estas variantes sejam as últimas. É impossível ter a certeza de como o vírus vai evoluir mas pesquisadores da Airfinity, na Inglaterra, empresa de dados de ciências da vida, tentaram mapear o local mais provável de aparecimento da próxima variante. A mutação de um vírus é um processo aleatório e é por isso que novas variantes bem-sucedidas são mais propensas a vir de lugares onde muitas mutações estão ocorrendo. A hipótese da Airfinity é de que vai ocorrer num local onde poucas pessoas estarão vacinadas e onde muitos sofrem com sistemas imunológicos enfraquecidos. As pessoas imunocomprometidas tendem a abrigar o vírus por mais tempo porque os respetivos corpos lutam mais para o combater, dando mais tempo para que as mutações bem-sucedidas possam se acumular e são menos propensos a produzir anticorpos após serem vacinados, o que significa que têm menos proteção contra a reinfecção.'), 
    Pagina(5,'Ministério da Saúde decide não recomendar 4ª dose de vacina contra a Covid-19','/static/img/covid-news-6.jpg','Após reunião da Câmara Técnica de Assessoramento em Imunização da Covid-19 (CTAI), nesta sexta-feira (11), o Ministério da Saúde decidiu que não vai recomendar a quarta dose de vacina no Brasil. As informações foram antecipadas pela CNN ontem. Segundo fontes da câmara técnica, o entendimento é de que não há pesquisas científicas com dados suficientes que embasam um novo reforço de imunização para pessoas que não sejam imunossuprimidas. O comitê também analisou o cenário epidemiológico atual do país antes de chegar a esta conclusão. Ainda de acordo com técnicos que compõem o comitê técnico, neste momento não deve ser aplicada a quarta dose porque as pessoas que tomaram duas doses e o reforço, ou seja, estão com o esquema vacinal completo, continuam muito bem protegidas contra a Covid- 19 e o agravamento da doença. A pasta definiu o posicionamento depois que o estado de São Paulo ampliou a vacinação ao público em geral com idade acima de 60 anos, com previsão para começar a aplicar a quarta dose a partir do dia 4 de abril. Em entrevista à CNN, o coordenador-executivo do Comitê Científico do estado de São Paulo, João Gabbardo, analisou que há evidências e experiências de outros países que mostram um benefício da dose extra de vacina para os idosos.')  
]

lista_de_noticia = [
    Noticia(6,'Rio Branco e outras cidades do Baixo, Alto Acre e Purus avançam para bandeira verde em avaliação do Comitê Covid','https://s2.glbimg.com/Nb5ECEQh2dJEujNB0A8rpjPZMLg=/0x0:540x405/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2020/u/6/km22dOTRqekbmjdKBptA/capturar.jpg','As regionais do Baixo Acre, Alto Acre e Purus avançaram para a bandeira verde, que representa cuidado, na avaliação do Comitê de Acompanhamento Especial da Covid-19. Já as regionais Juruá e Tarauacá/Envira permaneceram em bandeira amarela, que é de atenção. Os dados foram divulgados nesta sexta-feira (1º) pelo governo do Acre e representa o período de avaliação do dia 13 a 26 de março. Na última avaliação, divulgada no dia 7 de março, o governador Gladson Cameli manteve todas as cidades do Acre em nível de atenção (bandeira amarela) na classificação de risco da pandemia até o dia 31 de março, após aumento de casos no mês de fevereiro.'),
    Noticia(7,'Boletim: Alagoas registra mais 3 mortes e 11 novos casos de Covid-19','https://tnh1-cdn2.cworks.cloud/fileadmin/_processed_/e/7/csm_csm_Coronavirus_-_Foto_Pixabay_3fb0570561_efa426ceae.jpg','O Boletim Epidemiológico da Secretaria de Estado da Saúde (Sesau), desta segunda-feira (4), apresenta 11 casos de Covid-19 em Alagoas. Dessa forma, o Estado tem um total de 296.263 casos confirmados do novo coronavírus até o momento, dos quais 145 estão em isolamento domiciliar. Outros 288.977 pacientes já finalizaram o período de isolamento, não apresentam mais sintomas e, portanto, estão recuperados da doença. Há 1.268 casos em investigação epidemiológica. Foram registrados três óbitos em território alagoano. Com isso, Alagoas tem 6.891 óbitos por Covid-19. Os casos confirmados de pessoas com a Covid-19 estão distribuídos nos 102 municípios alagoanos. Em relação ao quadro total de óbitos em Alagoas, estão confirmados 6.891 óbitos por Covid-19, mas, oito deles, eram de pessoas residentes em Pernambuco, São Paulo, Santa Catarina e Bahia, tendo como vítimas seis homens e duas mulheres. Dos 6.883 óbitos de pessoas residentes em Alagoas, 3.790 eram do sexo masculino e 3.093 do sexo feminino. Eram 3.061 pessoas que residiam em Maceió e as outras 3.822 moravam no interior do Estado, segundo o Centro de Informações Estratégicas de Vigilância em Saúde (Cievs), da Sesau.'),
    Noticia(8,'Covid-19: Amapá registra 2 novos casos e tem 5 internados; óbitos seguem em 2.126','https://s2.glbimg.com/TOdnQhCHM_UKd0fyx2GVrexAIV4=/0x0:800x450/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2022/Q/A/6iSOjXRDABni09iblyhQ/51835306572-82d8e28583-c.jpg','O Amapá não contabilizou mortes e registrou 2 novos casos conhecidos de Covid-19 nas últimas 24 horas. Os dados constam no boletim epidemiológico do governo desta segunda-feira (4). Com isso, o estado chega a 160.349 casos confirmados e 2.126 óbitos. Os recuperados somam 129.915 pessoas (81,02%). Especialistas acreditam que há muitos que não fazem o exame, que isto continua bastante necessário. Esses fatores podem ocultar muitos casos firmados de Covid-19 que deixam de entrar nas estatísticas oficiais.'),
    Noticia(9,'Amazonas tem 52 casos e uma morte por Covid nas últimas 24 horas','https://s2.glbimg.com/ofRXFF7TICmyY6GPkCklyDZ0hA4=/0x0:1280x853/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2022/E/8/Lv0YIoTKKH0iZAxZuA2w/whatsapp-image-2022-02-05-at-18.01.07.jpeg','O Amazonas registrou 52 novos casos e uma morte por Covid nas últimas 24 horas, de acordo com dados da Fundação de Vigilância em Saúde do Amazonas (FVS-AM). Uma nova morte pela doença também foi registrada na terça-feira (5). No total são 581.494 casos da doença no estado. O número de mortes subiu para 14.160.'),
    Noticia(10,'Bahia registra 1.200 casos ativos de Covid-19 e 2 óbitos; veja taxas de ocupação dos leitos','https://s2.glbimg.com/2XFGMiJdjQ8k96j5rDIIgh2dj48=/0x0:1197x750/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2021/i/1/zVnYrwRtSJ7mlAVEb0Bw/foto-mateus-pereira-govba-2-1-.jpg','A Bahia tem 1.200 casos ativos de Covid-19, segundo dados divulgados nesta quarta-feira (6), pela Secretaria Estadual da Saúde (Sesab). Além disso, nas últimas 24 horas, foram registrados 228 casos conhecidos da doença e dois óbitos. De acordo com a Sesab, dos 1.535.160 casos confirmados desde o início da pandemia, 1.504.226 são considerados recuperados e 29.734 tiveram óbito confirmado.'),
    Noticia(11,'Número de casos graves e óbitos por Covid caem 99% no Ceará, diz secretaria','https://s2.glbimg.com/f-FxLpblGz2HJ7BVcBhWh2aKHxM=/0x0:1280x853/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2020/9/L/TAxRTeRnqaQYupMBa99A/whatsapp-image-2020-05-05-at-12.53.41-1-.jpeg','Entre janeiro e março deste ano, o Ceará teve uma redução de 99% nos diagnósticos positivos para a Covid-19. As confirmações caíram de 234.027, em janeiro, para 1.911 em março. Os dados são da Secretaria da Saúde do Ceará (Sesa) disponibilizados na plataforma IntegraSUS. Na mesma tendência, segundo a Sesa, o número de mortes saiu de 934 para 122 no período, uma queda de 87%. O Ceará deu início a uma nova etapa na imunização com mais de 80 mil idosos estão aptos a receber a segunda dose de reforço da vacina contra a Covid-19. Nesta semana também foi iniciada a campanha de vacina contra a gripe, que prioriza os idosos na primeira etapa.'),
    Noticia(12,'Covid-19: DF passa de 11,6 mil mortes e registra 147 novos casos','https://s2.glbimg.com/2bChBNZvWe0m3WSGA060TI5bslU=/0x0:799x533/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2022/S/x/tuAUzXQ4qHJQuWxxEUPg/51797793228-530fa086ef-c.jpg','O Distrito Federal registrou 147 novos casos conhecidos de Covid-19 e mais 4 mortes pela doença, nesta quarta-feira (6). Desde o início da pandemia, 11.601 pessoas perderam a vida e 693.102 foram infectadas pelo novo coronavírus em Brasília. Segundo a Secretaria de Saúde, 98,2% dos pacientes de Covid, no DF, estão recuperados. A taxa de transmissão do vírus que na terça-feira (5), era 0,73 subiu e está em 0,74. O índice, quando abaixo 1, indica queda nas infecções.'),
    Noticia(13,'Covid-19: máscara e passaporte da vacina deixam de ser obrigatórios; ES não terá mais mapa de risco','https://www.es.gov.br/Media/PortalES/Noticias/13%C2%BA-MAPA-DE-RISCO---13-a-19.07.jpg','A partir desta quarta-feira (6), o uso de máscara deixa de ser obrigatório em todo o Espírito Santo. Em coletiva de imprensa realizada nesta tarde, o governador Renato Casagrande afirmou que, com os bons resultados no início de abril, redução do número de casos, óbitos e internações por covid-19 no Estado capixaba, o mapa da matriz de risco também não será mais elaborado. O passaporte vacinal também deixará de ser exigido.'),
    Noticia(14,'Goiânia passa a ter drive-thru para vacinação contra gripe e Covid-19','https://s2.glbimg.com/eG1YulAZZMW8hrXPFOZR5tgvIXo=/0x0:768x512/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2021/P/t/AXI2swQseyMHowI3SAbQ/whatsapp-image-2021-05-31-at-13.31.11-1-768x512.jpeg','A Secretaria Municipal de Saúde anunciou que Goiânia terá um drive-thru para vacinação contra a gripe e a Covid-19. A partir desta terça-feira (5), os moradores podem ser vacinados no estacionamento do Estádio Serra Dourada, sem agendamento. O atendimento será feito das 8h às 16h, de segunda-feira à sexta-feira. Com o local, a capital passa a ter 73 pontos de vacinação (veja abaixo os endereços). A prefeitura informou que até o dia 30 deste mês, podem tomar a vacina contra a gripe os idosos com 60 anos ou mais e trabalhadores da saúde. Depois do dia 2 de maio até 3 de junho, serão os outros grupos prioritários (veja a lista abaixo).'),
    Noticia(15,'Maranhão completa uma semana sem registro de mortes por Covid-19','https://s2.glbimg.com/7TzGzN6c5oC1ZD6SM9-a96iEdNg=/0x0:1024x683/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2021/g/Y/BPnsgKSKOARN0lCiLyuw/whatsapp-image-2021-12-27-at-14.26.13.jpeg','O Maranhão completou neste domingo (3) uma semana sem registro de mortes por Covid-19, segundo a Secretaria de Estado da Saúde (SES). Os registros são de 28 de março a 3 de abril e foram obtidos a partir do boletim epidemiológico que é divulgado diariamente pela pasta. Na mesma semana, foram 2.093 casos registrados da doença e está em tendência de queda. Neste domingo (3), 18 foram registrados na Ilha de São Luís e 4 nas remais regiões do estado.'),
    Noticia(16,'MT registra menor taxa de ocupação de leitos de UTI Covid em quase dois anos','https://s2.glbimg.com/Rk7UJQz12A8I39o3-MRf_aAJ1qQ=/0x0:1024x683/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2021/I/B/iT9iGcR22vAWHTzFxrXA/tch5376.jpg','Mato Grosso registrou nesta terça-feira (5) a menor taxa de ocupação de leitos de Unidade de Terapia Intensiva (UTI) para Covid-19 desde maio de 2020. De acordo com o boletim epidemiológico da Secretaria de Saúde (SES), a taxa de ocupação está em 20,35%. Com a queda nas internações, dois hospitais de Mato Grosso não possuem nenhum paciente internado em UTI. O Hospital Municipal de Juína e o Regional de Sinop, estão com os leitos de UTI exclusivos para pacientes com coronavírus vagos. Outros dois hospitais estão com a taxa de ocupação em 10%. O Hospital e Maternidade Santa Rita e o Hospital Vale do Guaporé estão com um paciente internado em cada unidade.'),
    Noticia(17,'MS registra 14 novos casos de Covid em quatro municípios nesta segunda-feira','https://midiamax.uol.com.br/wp-content/uploads/2022/04/00-29-01-2021-Vacina-IMG_4874.jpg.webp','A semana começa com 14 novos casos de Covid confirmados em Mato Grosso do Sul. Conforme boletim epidemiológico divulgado nesta segunda-feira (04) pela Secretaria de Estado de Saúde (SES) são 11 casos em Dourados, enquanto Campo Grande, São Gabriel do Oeste e Sidrolândia tiveram um novo caso cada. A média móvel está em 171 no […] O post MS registra 14 novos casos de Covid em quatro municípios nesta segunda-feira apareceu primeiro em Diário Digital. A semana começa com 14 novos casos de Covid confirmados em Mato Grosso do Sul. Conforme boletim epidemiológico divulgado nesta segunda-feira (04) pela Secretaria de Estado de Saúde (SES) são 11 casos em Dourados, enquanto Campo Grande, São Gabriel do Oeste e Sidrolândia tiveram um novo caso cada. A média móvel está em 171 no Estado. '),
    Noticia(18,'Covid-19: 22 pessoas morrem nas últimas 24 horas em Minas Gerais','https://s2.glbimg.com/KOBGFl3zslQ4wIchTsAzUtMPx-s=/0x0:858x483/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2020/A/s/YBnqBBRnGDcjiQTWkCtg/sars.jpg','Vinte e duas pessoas morreram nas últimas 24 horas em Minas Gerais por causa da Covid-19, informou, neste domingo (20), a Secretaria de Estado de Saúde (SES). Ainda segundo o órgão, no mesmo período, houve 1.158 casos da doença. Desde o início da pandemia, 3.296.877 pessoas testaram positivo para o coronavírus no estado. Destas, 3.168.768 são consideradas recuperadas. Outros 67.549 pacientes estão em acompanhamento.'),
    Noticia(19,'Pará registra 756.881 casos e 18.125 mortes por Covid-19','https://s2.glbimg.com/MW0_5yUtU0LuveAxpAzrvnFlJz4=/0x0:1920x960/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2021/Q/x/B8DlKjT12NHuoC9jAmYQ/virus-molecula-covid-19-coronavirus-cred-peter-linforth-pixabay.jpg','O Pará contabilizou mais 757 casos de Covid-19 e 4 mortes causadas pela doença, segundo o boletim divulgado pela Secretaria de Saúde Pública do Pará (Sespa) nesta segunda-feira (4). Agora são 756.881 pessoas diagnosticadas com a doença desde março de 2020, sendo que 18.125 morreram. Houve 6 casos confirmados e uma morte registrada nos últimos sete dias. Em relação à subnotificação das prefeituras, foram confirmados mais 751 casos e 3 mortes ocorridas em dias anteriores.'),
    Noticia(20,'Novo decreto de João Pessoa volta a exigir teste negativo de Covid-19 para acesso a shows','https://s2.glbimg.com/DrP-mhNs_x6_5JNFjaxflzVJ35k=/0x0:400x267/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2020/W/X/Hd2ThcR76W4h8Bh3EPgA/whatsapp-image-2020-10-22-at-16.16.14.jpeg','A Prefeitura de João Pessoa publicou no Diário Oficial Eletrônico deste sábado (2) um novo decreto com medidas de enfrentamento e prevenção à pandemia da Covid-19. O documento mantém as mesmas regras do anterior, com algumas exceções, e tem validade até o dia 7 de abril, data em que também perderá o vigor o decreto estadual. De acordo com o decreto, uma das mudanças em relação ao decreto anterior é inclusão da obrigatoriedade da apresentação de teste de antígeno negativo para Covid-19, realizado em até 72 horas antes dos eventos, para o ingresso em shows.'),
    Noticia(21,'Nove dias após liberação das máscaras ao ar livre, números da pandemia seguem em queda','https://www.aen.pr.gov.br/sites/default/arquivos_restritos/files/imagem/2022-03/mascaras3.jpg','Nove dias após a liberação do uso de máscaras em ambientes externos no Paraná, a Secretaria de Estado da Saúde (Sesa) analisou os números da pandemia para avaliar se o decreto governamental e a resolução da pasta interferiram na curva de contaminados. Neste sábado (26), o Estado completa dez dias sem a obrigatoriedade do uso ao ar livre ou para crianças menores de 12 anos. Os números de casos, óbitos e internações pela Covid-19 já apresentavam queda significativa quando a medida foi tomada e, agora, mais de uma semana após a liberação, a redução é ainda maior. A taxa de reprodução eficaz, ou Rt, número médio de contágios causados por cada pessoa infectada, indica a velocidade de contaminação da Covid-19 em cada localidade. Atualmente o Paraná está com 0,92, o que significa que 100 pessoas contaminadas pelo vírus Sars-CoV-2 transmitem, em média, para 92 novas pessoas. Os números são diferentes dos registros de 13 de janeiro, no pico da Ômicron, quando o Paraná atingiu o maior RT desde o início da pandemia, com 1,92.'),
    Noticia(22,'Pernambuco registra, nesta quinta (7), sete mortes e 1.378 casos da Covid-19','https://cdn.folhape.com.br/img/pc/1100/1/dn_arquivo/2022/01/mg-2895-credito-miva-filho-ses-pe.webp','Sete óbitos e 1.378 casos da Covid-19 foram registrados em Pernambuco, nesta quinta-feira (7), pela Secretaria Estadual de Saúde (SES-PE). Agora Pernambuco contabiliza 21.461 mortes pela Covid-19 e 905.319 casos confirmados da doença, sendo 58.388 graves e 846.931 leves.'),
    Noticia(23,'Mulher de 31 anos morre vítima da Covid-19 em Teresina; Piauí chega a 7.708 óbitos pela doença','https://s2.glbimg.com/gqPgpVDzr64GvGksuEgJnQDuyAI=/0x0:5500x3666/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2021/j/m/ZxIH2JTjWBX2IQQcSb8Q/2021-07-10t143639z-1788242058-rc2tfo9b6pug-rtrmadp-3-global-population-brazil.jpg','Uma mulher de 31 anos, de Teresina, morreu vítima da Covid-19, segundo o boletim epidemiológico da Secretaria de Saúde do Piauí (Sesapi) divulgado nesta terça-feira (15). Além dela, uma idosa de 87 anos, residente no município de Nossa Senhora dos Remédios, e um idoso de 77 anos, de São Pedro do Piauí, faleceram em decorrência da doença. O estado também registrou 160 novos casos da Covid-19. Do total, 99 são mulheres e 61 são homens, com idades que variam de 02 a 81 anos. Os casos confirmados no estado somam 366.815 em todos os municípios piauienses. Já os óbitos pelo novo coronavírus chegam 7.708 casos e foram registrados em 224 municípios.'),
    Noticia(24,'Mapa de Risco da Covid-19: estado do Rio de Janeiro volta para bandeira verde','https://www.saude.rj.gov.br/comum/code/MostrarImagem.php?C=NDgxNDE%2C','A 72ª edição do Mapa de Risco da Covid-19, divulgada nesta sexta-feira (11.03) pela Secretaria de Estado de Saúde (SES), mostra que o estado do Rio de Janeiro voltou para a bandeira verde (risco muito baixo) após um período de três meses. A análise compara a sétima semana epidemiológica (SE 07) deste ano, 13/02/2022 a 19/02/2022, com a nona semana (SE 09), 27/02/2022 a 05/03/2022. O mapa desta semana mostra que a Região Metropolitana I saiu da bandeira amarela (risco baixo) e está em bandeira verde (risco muito baixo). A Região Metropolitana II se manteve em bandeira verde (risco muito baixo). A Região Centro-Sul também apresentou melhora, saindo da bandeira laranja (risco moderado) para a bandeira amarela (risco baixo). As regiões do Médio Paraíba, Serrana, Norte, Baixada Litorânea e Baía da Ilha Grande permaneceram com bandeira amarela (risco baixo). A Região Noroeste se manteve em bandeira laranja (risco moderado).'),
    Noticia(25,'Governo do RN anuncia desobrigação do uso de máscaras em locais fechados','https://s2.glbimg.com/5F8GEbtqfsjodDP2k5xkWiE0Jog=/0x0:1600x900/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2022/H/n/vPbsgHRPqeY6E1gGxAwA/whatsapp-image-2022-03-10-at-12.58.06-1-.jpeg','O governado do Rio Grande do Norte anunciou a desobrigação do uso de máscaras em locais abertos e fechados do estado a partir desta quarta-feira (6). Segundo o poder Executivo, a flexibilização atendeu uma recomendação do comitê científico da Secretaria de Estado da Saúde Pública (Sesap) que discutiu o assunto em uma reunião na noite de terça-feira (5).'),
    Noticia(26,'Covid: 161,6 milhões de brasileiros completam vacinação, 75,2% da população.','https://conteudo.imguol.com.br/c/noticias/68/2022/01/24/crianca-e-vacinada-em-drive-thru-no-municipio-de-osasco-na-grande-sao-paulo-1643049642579_v2_900x506.jpg.webp','Hoje (6), o Brasil chegou à marca de 161,6 milhões de pessoas que completaram a vacinação contra a covid-19. Ao todo, 161.626.084 habitantes receberam a segunda dose ou a dose única de imunizante, o que representa 75,23% da população nacional. As informações foram compiladas pelo consórcio de veículos de imprensa do qual o UOL faz parte, a partir das informações fornecidas pelas secretarias estaduais de saúde. O ciclo vacinal foi concluído por 243.680 brasileiros entre ontem e hoje, com a aplicação de 239.697 segundas doses e 3.983 únicas. Neste período, 106.186 pessoas tomaram a primeira e 367.582 a de reforço, totalizando 717.448 doses ministradas nas últimas 24 horas.'),
    Noticia(27,'Casos de Covid aumentam em Rondônia na 1ª semana da liberação de máscaras','https://s2.glbimg.com/2zQfBbJTKuEvTdkAveXKkHwhmhg=/0x0:2638x1570/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2021/n/e/A3AzTiT0On8B4jKeN9Pg/covid-rt.jpg','Rondônia registrou um aumento de 62% de casos Covid na primeira semana em que o uso de máscara passou a ser facultativo no estado, tanto em ambientes fechados quanto abertos. Segundo dados disponibilizados no boletim da Secretaria de Estado da Saúde (Sesau), entre a segunda-feira (14) e o sábado (19) foram 3.536 novos casos conhecidos de Covid registrados em sistema. Já na semana anterior, entre 7 e 12 de março, Rondônia teve 2.180 casos em seis dias. Mesmo com o aumento de casos nesta terceira semana do mês, o número ainda ficou abaixo do registrado na primeira semana de março, quando foram 5.728 casos de Covid em cinco dias. Nessa época, o uso de máscara ainda era obrigatório em Rondônia.'),
    Noticia(28,'Uso de máscaras em locais fechados será facultativo, diz prefeitura de Boa Vista','https://s2.glbimg.com/fb7RusFThWfyx5_9vgt5ROp0tEc=/0x0:1600x900/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2022/c/X/JvzCaoSZeeXJlUXj8mzA/whatsapp-image-2022-03-10-at-12.58.07.jpeg','A prefeitura de Boa Vista anunciou nesta terça-feira (5), que vai tornar facultativo o uso de máscaras faciais de proteção contra a Covid-19 em locais fechados na capital. O decreto com esta e outras flexibilizações deve ser publicado no Diário Oficial da quarta-feira (6). O município acrescentou que, apesar do uso passar a ser facultativo, a população deverá seguir algumas orientações que serão disponibilizadas no decreto.'),
    Noticia(29,'Coronavírus em SC: Estado confirma 1.680.292 casos, 1.655.116 recuperados e 21.682 mortes','https://www.sc.gov.br/images/joomgallery/details/setoriais_6457/boletim_05_04_2022_20220405_1693381039.jpeg','Santa Catarina tem 1.680.292 pacientes com teste positivo para Covid-19. Desses, 1.655.116 são considerados recuperados e 3.494 continuam em acompanhamento. O dado foi divulgado nesta terça-feira, 5. Até hoje, 21.682 óbitos foram causados pelo novo coronavírus. Esses números colocam a taxa de letalidade em 1,29%. Houve mais 9 óbitos registrados em comparação com o dia anterior. O total de confirmados cresceu 1.314, enquanto 1.246 pessoas passaram a se enquadrar nos critérios para serem consideradas recuperadas. Esses dados resultam num crescimento de 59 no número de casos ativos.'),
    Noticia(30,'SP tem a menor média móvel de óbitos por Covid-19 desde pico da Ômicron','https://imagens.ebc.com.br/OahA7IYqXAnnbpkTCasXkThXpJA=/1170x700/smart/https://agenciabrasil.ebc.com.br/sites/default/files/thumbnails/image/img_7082.jpg?itok=KYPWhTYx','São Paulo tem a menor média móvel de mortes por Covid-19 desde o pico da variante Ômicron. O estado registrou nesta quarta-feira (6) 42 mortes pela doença na média móvel de 7 dias. “Os dados epidemiológicos da última semana apontam um controle da pandemia no estado com a queda novos casos e óbitos e estabilidade nas novas internações. Os altos índices de vacinação pavimentaram um caminho seguro do enfrentamento da pandemia em SP”, destaca o Secretário de Estado da Saúde, Jean Gorinchteyn. Os novos casos na semana registraram uma redução de 16,6%, tendo um total de 5.287.122 durante toda a pandemia. Entre as internações, o estado tem hoje 1.672 pessoas internadas, sendo 561 em Unidades de Terapia Intensiva e 1.111 em enfermaria. Comparado com o pico da variante Ômicron, o estado de São Paulo tem queda de 86%.'),
    Noticia(31,'Sergipe registra 204 novos casos conhecidos de Covid-19 e três mortes','https://s2.glbimg.com/JPRrB3A_IT2W13vrR-ph52EvO98=/0x0:1024x768/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2022/Z/6/6BSWK6TyeshAOV3rwMsg/noticias.sorocaba.sp.gov.br-drive-thru-a-fome-nao-e-fake-socorro-a-petropolis-tem-testagem-rapida-de-covid-19-neste-domingo-20-e-mais-parcerias-na-arrecadacao-de-alimentos-teste.jpg','Mais de 200 novos casos conhecidos de Covid-19 e três mortes em decorrência da doença foram registradas em Sergipe neste sábado (12), pela Secretaria da Saúde de Sergipe (SES). Os três óbitos confirmados foram: uma mulher, 55 anos, de Aracaju, com doença cardiovascular crônica, diabetes e doença renal crônica; um homem, 67 anos, de São Cristóvão, com hipertensão, diabetes, obesidade, doença pulmonar obstrutiva crônica e tabagismo; um homem, 72 anos, de Tobias Barreto, com neoplasia.'),
    Noticia(32,'Os três óbitos confirmados foram: uma mulher, 55 anos, de Aracaju, com doença cardiovascular crônica, diabetes e doença renal crônica; um homem, 67 anos, de São Cristóvão, com hipertensão, diabetes, obesidade, doença pulmonar obstrutiva crônica e tabagismo; um homem, 72 anos, de Tobias Barreto, com neoplasia.','https://s2.glbimg.com/EQf3t-YfwxG5Lym1xB_C6JjGkoU=/0x0:1280x1002/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2021/G/G/VjCAYITbyBnOJyL9Cw7Q/whatsapp-image-2021-11-18-at-14.24.39.jpeg','Araguaína e Gurupi, duas das principais acidades do Tocantins, ultrapassaram a marca de 70% da população vacinada com pelo menos uma dose contra Covid-19. Nesta semana as vacinas continuam sendo aplicadas para todos os públicos. Para vacinação dos menores de 18 anos é necessária presença dos pais ou representantes legais, ou envio de um termo de consentimento com o representante. Também é necessária identificação com foto, CPF e cartão de vacina para todos os públicos.')
]
listas_de_paginas_estado =[
    Estado(0,'Acre','/static/img/bandeiras/Acre.png'),
    Estado(1,'Alagoas','/static/img/bandeiras/Alagoas.png'),
    Estado(2,'Amapá','/static/img/bandeiras/Amapá.png'),
    Estado(3,'Amazonas','/static/img/bandeiras/Amazonas.png'),
    Estado(4,'Bahia','/static/img/bandeiras/Bahia.png'),
    Estado(5,'Ceará','/static/img/bandeiras/Ceará.png'),
    Estado(6,'Distrito Federal','/static/img/bandeiras/Distrito_federal.png'),
    Estado(7,'Espírito Santo','/static/img/bandeiras/Espirito_santos.png'),
    Estado(8,'Goiás','/static/img/bandeiras/Goias.png'),
    Estado(9,'Maranhão','/static/img/bandeiras/Maranhão.png'),
    Estado(10,'Mato Grosso','/static/img/bandeiras/Mato_grosso.png'),
    Estado(11,'Mato Grosso do Sul','/static/img/bandeiras/Mato_grosso_do_sul.png'),
    Estado(12,'Minas Gerais','/static/img/bandeiras/Minas_gerais.png'),
    Estado(13,'Pará','/static/img/bandeiras/Pará.png'),
    Estado(14,'Paraíba','/static/img/bandeiras/Paraiba.png'),
    Estado(15,'Paraná','/static/img/bandeiras/Paraná.png'),
    Estado(16,'Pernambuco','/static/img/bandeiras/Pernambuco.png'),
    Estado(17,'Piauí','/static/img/bandeiras/Piaui.png'),
    Estado(18,'Rio de Janeiro','/static/img/bandeiras/Rio_de_janeiro.png'),
    Estado(19,'Rio Grande do Norte','/static/img/bandeiras/Rio_grande_do_norte.png'),
    Estado(20,'Rio Grande do Sul','/static/img/bandeiras/Rio_grande_do_sul.png'),
    Estado(21,'Rondônia','/static/img/bandeiras/Rondonia.png'),
    Estado(22,'Roraima','/static/img/bandeiras/Roraima.png'),
    Estado(23,'Santa Catarina','/static/img/bandeiras/Santa_catarina.png'),
    Estado(24,'São Paulo','/static/img/bandeiras/Sao_paulo.png'),
    Estado(25,'Sergipe','/static/img/bandeiras/Sergipe.png'),
    Estado(26,'Tocantins','/static/img/bandeiras/Tocantins.png')
]

@app.route('/')
def home():
    return render_template('index.html',paginas=listas_de_paginas_principais,paginas_2=listas_de_paginas_recentes,paginas_3=listas_de_paginas_estado, pagina_4=lista_de_noticia)

@app.route('/manutencao/')
def manutencao():
    return render_template('manutencao.html')

@app.route('/news-1/<id>')
def Principais(id):
    for pagina in listas_de_paginas_principais:
        if pagina.get_id() == int(id):
            return render_template('principais.html',principais=pagina)
    return render_template('index.html',principais=listas_de_paginas_principais[int(id)])
    
@app.route('/news-2/<id>')
def Recentes(id):
    for pagina in listas_de_paginas_recentes:
        if pagina.get_id() == int(id):
            return render_template('Recentes.html',recentes=pagina)
    return render_template('index.html',recentes=listas_de_paginas_recentes[int(id)])

@app.route('/estado/<id>')
def Estados(id):
    for pagina in lista_de_noticia:
        if pagina.get_id() == int(id):
            return render_template('Estado.html',estado=pagina)
    return render_template('Estado.html',noticia=lista_de_noticia[int(id)])

@app.route('/noticia/<id>')
def noticia(id):
    for pagina in lista_de_noticia:
        if pagina.get_id() == int(id):
            return render_template('Noticia.html',noticia=pagina)
    return render_template('Noticia.html',noticia=listas_de_paginas_principais[int(id)])

if __name__ == '__main__':
    app.run(debug=True)
